#!/usr/bin/env python3
import requests

from pprint import pprint

def pp(obj, depth=None):
  pprint(obj, depth=depth)

def ppd(obj, depth=None):
  pp(dir(obj), depth=depth)

def splitQS(qs):
  lines = qs.split('&')
  d = [l.split('=') for l in lines]
  return d

print()
print("Loading...")
print("requests")
print("pp(obj, depth=None)")
print("ppd(obj, depth=None)")
print("splitQS(qs)")
print()
print("Have a nice day!")
