#!/usr/bin/env python3
import requests

from pprint import pprint

def pp(obj, depth=None):
  pprint(obj, depth=depth)

def ppd(obj, depth=None):
  pp(dir(obj), depth=depth)

print()
print("Loaded requests, pp(), and ppd() from .pythonrc!")
print("Have a nice day!")
